name: Deploy Wedding Front App

env:
  API_SERVER: ${{ vars.API_SERVER }}

on:
  workflow_dispatch:
  push:
    paths-ignore:
      - '.github/**'
    branches:
      - main

jobs:
  setup:
    name: Setup Build Environment
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node version
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install dependencies
        run: |
          corepack enable
          corepack prepare pnpm --activate
          pnpm install

  build:
    name: Build Angular App
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node version
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: enabling Corepack and check pnpm version
        run: |
          corepack enable
          corepack prepare pnpm --activate
          pnpm --version

      - name: Build App
        run: pnpm build

      - name: Upload dist Dir
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist

  deploy:
    name: Deploy to S3 and Invalidate CloudFront
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download dist Dir
        uses: actions/download-artifact@v4
        with:
          name: dist

      - name: Deploy to S3 Storage
        uses: jakejarvis/s3-sync-action@v0.5.1
        with:
          args: --follow-symlinks --delete
        env:
          AWS_S3_BUCKET: ${{ secrets.S3_BUCKET_NAME }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          SOURCE_DIR: dist

      - name: Invalidate CloudFront
        uses: chetan/invalidate-cloudfront-action@v2
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          DISTRIBUTION: ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }}
          PATHS: '/*'
